# Generated by Django 4.1.7 on 2023-05-03 19:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_checkoutadress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckoutAdress',
            new_name='CheckoutAddress',
        ),
        migrations.RenameField(
            model_name='checkoutaddress',
            old_name='street_adress',
            new_name='street_address',
        ),
    ]
