# Generated by Django 4.1.7 on 2023-05-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_checkoutadress_checkoutaddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutaddress',
            old_name='apartment_adress',
            new_name='apartment_address',
        ),
    ]
