# Generated by Django 4.1.7 on 2023-05-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_apartment_adress_checkoutaddress_apartment_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
